### ISSUE TITLE
i cant download sdcc toolchains on linux i686

### ISSUE THREAD

**Issue by kenzanin** [platformio/platform-intel_8051#2]
Error: Could not install 'toolchain-sdcc' with version requirements '~1.30603' for your system 'linux_i686'.
If you use Antivirus, it can block PlatformIO Package Manager. Try to disable it for a while.

**Comment by Palatis** [comment]
weird, this is a really strange problem.

I have [toolchain-sdcc-i386-unknown-linux2.5-1.30603.9771.tar.bz2](https://dl.bintray.com/palatis/platformio-dl-packages/) under [](https://dl.bintray.com/palatis/platformio-dl-packages/toolchain-sdcc-i386-unknown-linux2.5-1.30603.9771.tar.bz2), but the file in then [manifest.json](https://dl.bintray.com/palatis/platformio-dl-packages/manifest.json) is listing toolchain-sdcc-i386-unknown-linux2.**6**-1.30603.9771.tar.bz2 for no reason...

maybe just try with a amd64 machine FTM, I might sync the SDCC package with upstream when I have some free time.

**Comment by kenzanin** [comment]
thanks i will try it soon, and report back to you. sorry for late replay.

**Comment by ivankravets** [comment]
Fixed
